# Generated by Django 5.0.6 on 2024-06-26 01:44

import Taskpilot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField(max_length=400)),
                ('task_deadline', models.DateField(validators=[Taskpilot.models.future_date_validator])),
            ],
        ),
    ]
