# Generated by Django 5.0.6 on 2024-07-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskpilot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=10)),
                ('student_age', models.IntegerField()),
                ('student_class', models.CharField(max_length=20)),
            ],
        ),
    ]
